version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: install_httpd.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: restart_httpd.sh
      timeout: 300
      runas: root
