version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js"
      - curl -fsSL https://rpm.nodesource.com/setup_18.x | bash -
      - yum install -y nodejs
      - node -v
      - npm -v
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building application"
      - mkdir -p /tmp/html
      - cp index.html /tmp/html/
  post_build:
    commands:
      - echo "configuring the application"
artifacts:
  files:
    - '**/*'
