version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies"
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo "Building application"
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo "configuring ngnix"
artifacts:
  files:
    - '**/*'

